LitReview/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('reviewer.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviewer/urls.py
from django.urls import path

from . import views

app_name = 'reviewer'
urlpatterns = [
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', views.MyLogoutView.as_view(), name='logout'),
    path('register/', views.MyRegisterView.as_view(), name='register'),

    path('', views.HomePage.as_view(), name='home'),
    path('flux/', views.FluxView.as_view(), name='flux'),
    path('my_posts/', views.CurrentUserPostsView.as_view(), name='my_posts'),

    path('ticket-create/', views.CreateTicketView.as_view(), name='create_ticket'),
    path('ticket-update/<int:pk>/', views.UpdateTicketView.as_view(), name='update_ticket'),
    path('ticket-delete/<int:pk>/', views.DeleteTicketView.as_view(), name='delete_ticket'),

    path('review-update/<int:pk>/', views.UpdateReviewView.as_view(), name='update_review'),
    path('review-create/<int:pk>/', views.CreateReviewFromTicketView.as_view(), name='create_review'),
    path('review-ticket-create/', views.CreateReviewWithoutTicketView.as_view(), name='create_review_ticket'),
    path('review-delete/<int:pk>/', views.DeleteReviewView.as_view(), name='delete_review'),

    path('subscription/', views.SearchUserView.as_view(), name='list_subscriber'),
    path('subscribe/', views.SubscribeView.as_view(), name='subscribe'),
    path('unsubscribe/', views.UnsubscribeView.as_view(), name='unsubscribe'),
]

Reviewer/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class MyAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].label = ''
        self.fields['username'].widget.attrs.update(
            {
                'placeholder': "Nom d'utilisateur",
            }
        )

        self.fields['password'].label = ''
        self.fields['password'].widget.attrs.update(
            {
                'placeholder': 'Mot de passe',
            }
        )


class MyUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].label = ''
        self.fields['username'].widget.attrs.update(
            {
                'placeholder': "Nom d'utilisateur",
            }
        )

        self.fields['password1'].label = ''
        self.fields['password1'].widget.attrs.update(
            {
                'placeholder': 'Mot de passe',
            }
        )

        self.fields['password2'].label = ''
        self.fields['password2'].widget.attrs.update(
            {
                'placeholder': 'Confirmez mot de passe',
            }
        )

reviewer/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.exceptions import ValidationError
from django.forms.widgets import Textarea

from .models import Review, Ticket


class MyAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].label = ''
        self.fields['username'].widget.attrs.update(
            {
                'placeholder': "Nom d'utilisateur",
            }
        )

        self.fields['password'].label = ''
        self.fields['password'].widget.attrs.update(
            {
                'placeholder': 'Mot de passe',
            }
        )


class MyUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].label = ''
        self.fields['username'].widget.attrs.update(
            {
                'placeholder': "Nom d'utilisateur",
            }
        )

        self.fields['password1'].label = ''
        self.fields['password1'].widget.attrs.update(
            {
                'placeholder': 'Mot de passe',
            }
        )

        self.fields['password2'].label = ''
        self.fields['password2'].widget.attrs.update(
            {
                'placeholder': 'Confirmez mot de passe',
            }
        )

        # Bootstrap class name for style
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class TicketForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Bootstrap class name for style
        for field in self.fields.values():
            class_name = {'class': 'form-control'}
            field.widget.attrs.update(class_name)

    class Meta:
        model = Ticket
        fields = ['title', 'description', 'image']
        exclude = ['time_created', ]


class ReviewFromTicketForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Bootstrap class name for style
        for field in self.fields.values():
            class_name = {'class': 'form-control'}
            field.widget.attrs.update(class_name)

    class Meta:
        model = Review
        fields = ['rating', 'headline', 'body']
        exclude = ['time_created', ]


class ReviewWithoutTicketForm(forms.Form):
    # Ticket fields
    title = forms.CharField(label='Titre', max_length=128)
    description = forms.CharField(label='Description', max_length=2048, widget=Textarea, required=False)
    image = forms.ImageField(label='Image', required=False)

    # Review fields
    rating = forms.IntegerField(label='Note')
    headline = forms.CharField(label='Titre', max_length=128)
    body = forms.CharField(label='Commentaire', max_length=8192, widget=Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Bootstrap class name for style
        for field in self.fields.values():
            class_name = {'class': 'form-control'}
            field.widget.attrs.update(class_name)

    def clean_rating(self):
        rating = self.cleaned_data['rating']
        if not (0 <= rating <= 5) and (rating % 2 != 0):
            raise ValidationError("La note doit être un entier positif entre 0 et 5")
        return rating

reviewer/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, TemplateView
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, FormView, ListView, UpdateView, View

from .forms import MyAuthenticationForm, MyUserCreationForm, ReviewFromTicketForm, ReviewWithoutTicketForm, TicketForm
from .mixins import AnonymousMixins
from .models import Review, Ticket, UserFollows

# =========================================================================================
# =========================================================================================
# TODO : error message when wrong credential
# =========================================================================================
# =========================================================================================

class MyLoginView(LoginView):
    template_name = 'reviewer/login.html'
    form_class = MyAuthenticationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('reviewer:flux')
    extra_context = {
        'submit_button': 'Connexion',
    }


class MyLogoutView(LogoutView):
    pass


class MyRegisterView(AnonymousMixins, CreateView):
    template_name = 'reviewer/register.html'
    form_class = MyUserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('reviewer:flux')
    extra_context = {
        'submit_button': "S'inscrire",
    }

    def form_valid(self, form):
        redirect_page = super().form_valid(form)
        user = form.save()
        if user is not None:
            login(self.request, user)
        return redirect_page


class HomePage(LoginRequiredMixin, TemplateView):
    def get(self, request, *args, **kwargs):
        return redirect('reviewer:flux')


class CreateTicketView(LoginRequiredMixin, CreateView):
    template_name = 'reviewer/create_ticket.html'
    success_url = reverse_lazy('reviewer:flux')
    model = Ticket
    form_class = TicketForm
    extra_context = {
        'submit_button': 'Envoyer',
        'enctype': 'multipart/form-data',
    }

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class DeleteTicketView(LoginRequiredMixin, DeleteView):
    model = Ticket
    template_name = 'reviewer/delete_ticket.html'
    context_object_name = 'ticket'
    success_url = reverse_lazy('reviewer:my_posts')
    extra_context = {
        'submit_button': 'Confirmer'
    }


class DetailTicketView(LoginRequiredMixin, DetailView):
    model = Ticket
    context_object_name = 'ticket'


class ReviewsAndTicketsAdapter(ListView):
    context_object_name = 'flux_elements'

    def create_flux_elements(self, intermediate_queryset) -> list:
        """
        Creating dict for each element. ==>
        {
          'review': review or None if is a review,
          'ticket': ticket or None if is a ticket,
        }
        """
        queryset = []
        for elem in intermediate_queryset:
            if type(elem) == Review:
                flux_elements = {
                    'review': elem,
                    'ticket': None,
                    'rating': f'star_{elem.rating}.png'
                }
            else:
                flux_elements = {
                    'review': None,
                    'ticket': elem,
                }
            queryset.append(flux_elements)
        return queryset


class FluxView(LoginRequiredMixin, ReviewsAndTicketsAdapter):
    """
    The 'Flux'
    This is the list with all tickets and reviews
    including those whom don't belongs to the loged user.
    """
    model = Ticket
    template_name = 'reviewer/flux.html'

    def get_queryset(self):
        """
        Only one list containing both tickets with review and tickets not reviewed yet.
        The reason they are not in two separate context is because this way is easier
        for sorting by time_created.
        """
        followed_users_queryset = UserFollows.objects.filter(
            user=self.request.user
        ).values_list('followed_user', flat=True)

        # We add the current user to display followed_users and own's tickets.
        followed_users = [self.request.user]
        # This loop is just to avoid loading the whole result in memory :
        for user in followed_users_queryset:
            followed_users.append(user)

        tickets = super().get_queryset().filter(user__in=followed_users)
        # We fetch reviews of already reviewed tickets in the same list to sort by time_created :
        intermediate_queryset = []
        # id of ticket already reviewed by current user :
        reviewed_ticket_id = []
        for ticket in tickets:
            intermediate_queryset.append(ticket)
            if reviews := ticket.reviews.all():
                for review in reviews:
                    if review.user_id == self.request.user.id:
                        reviewed_ticket_id.append(review.ticket_id)
                intermediate_queryset.extend(reviews)
        intermediate_queryset.sort(key=lambda elem: elem.time_created, reverse=True)

        queryset = self.create_flux_elements(intermediate_queryset)

        return queryset


class CurrentUserPostsView(LoginRequiredMixin, ReviewsAndTicketsAdapter):
    """
        'The posts'
        This is the list of tickets and reviews created by
        the current user.
        """
    model = Review
    template_name = 'reviewer/my_posts.html'

    def get_queryset(self):
        user = self.request.user
        intermediate_queryset = []
        intermediate_queryset.extend(user.reviews.all())
        intermediate_queryset.extend(user.tickets.all())
        intermediate_queryset.sort(key=lambda elem: elem.time_created, reverse=True)

        queryset = self.create_flux_elements(intermediate_queryset)
        return queryset


class CreateReviewFromTicketView(LoginRequiredMixin, CreateView):
    template_name = 'reviewer/create_review.html'
    success_url = reverse_lazy('reviewer:my_posts')
    model = Review
    form_class = ReviewFromTicketForm
    extra_context = {
        'submit_button': 'Envoyer',
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket'] = Ticket.objects.get(pk=self.kwargs.get('pk'))
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.ticket_id = self.kwargs.get('pk')
        return super().form_valid(form)


class CreateReviewWithoutTicketView(LoginRequiredMixin, FormView):
    template_name = 'reviewer/create_ticket_n_review.html'
    success_url = reverse_lazy('reviewer:my_posts')
    form_class = ReviewWithoutTicketForm
    extra_context = {
        'submit_button': 'Envoyer',
        'enctype': 'multipart/form-data',
    }

    def form_valid(self, form):
        user = self.request.user
        ticket = Ticket.objects.create(
            user=user,
            **{
                'title': form.cleaned_data['title'],
                'description': form.cleaned_data['description'],
                'image': form.cleaned_data['image'],
            }
        )
        Review.objects.create(
            user=user,
            **{
                'ticket': ticket,
                'rating': form.cleaned_data['rating'],
                'headline': form.cleaned_data['headline'],
                'body': form.cleaned_data['body'],
                'time_created': ticket.time_created,
            }
        )
        return super().form_valid(form)


class DeleteReviewView(LoginRequiredMixin, DeleteView):
    model = Review
    template_name = 'reviewer/delete_review.html'
    context_object_name = 'review'
    success_url = reverse_lazy('reviewer:my_posts')
    extra_context = {
        'submit_button': 'Confirmer'
    }


ERROR = {
    'subscription_exist': 'Cet abonnement existe déjà !',
    'no_subscription': 'Cet abonnement n\'existe pas',
}


class SearchUserView(LoginRequiredMixin, ListView):
    """
    View gives the list of users followed and the list of is_following users.
    """
    template_name = 'reviewer/list_followed_user.html'
    model = User
    context_object_name = 'searched_users'
    no_user_found = False

    def get_queryset(self, *args, **kwargs):
        searched_users = []
        pk = self.request.user.pk
        if name := self.request.GET.get('name'):
            users = super().get_queryset(*args, **kwargs).exclude(pk=pk).filter(username__icontains=name)
            user_followed = [
                user.followed_user
                for user in self.request.user.is_following.all()
            ]
            for user in users:
                if user not in user_followed:
                    searched_users.append(user)
            if not searched_users:
                self.no_user_found = True
        return searched_users

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['followed_users'] = UserFollows.objects.filter(user=self.request.user)
        context['following_users'] = UserFollows.objects.filter(followed_user=self.request.user)
        if self.no_user_found:
            context['error'] = "L'utilisateur recherché n'existe pas ou est déjà suivit."
        else:
            context['error'] = ERROR.get(self.request.GET.get('error'), '')

        return context


class SubscribeView(LoginRequiredMixin, View):
    """
    A subscribe user inside of the user followed page. Supporting only POST method.
    """

    def get(self, request, *args, **kwargs):
        # check if user not already followed
        if self.request.user.is_following.filter(followed_user_id=self.request.GET.get('user_id')):

reviewer/templates/reviewer/create_review.html
{% extends 'squeleton.html' %}

{% block title %}
    <title>Creation de critique</title>
{% endblock title %}


{% block content %}
    <div class="border border-dark p-3">
        <h4>Vous êtes en tain de poster en réponse à :</h4>
        <div class="container col-md-8 border border-dark">
            {% include 'reviewer/detail_ticket.html' with ticket=ticket %}
        </div>
    </div>
    <h2>Création de critique</h2>
    {% include 'reviewer/form/full.html' %}
{% endblock content %}

reviewer/templates/reviewer/create_ticket.html
{% extends 'squeleton.html' %}

{% block title %}
    <title>Creation de ticket</title>
{% endblock title %}

{% block content %}
    <h2>Création de ticket</h2>
    {% include 'reviewer/form/full.html' %}
{% endblock content %}

reviewer/templates/reviewer/create_ticket_n_review.html
{% extends 'squeleton.html' %}

{% block title %}
    <title>Creation de critique</title>
{% endblock title %}


{% block content %}
    <h2>Création de critique :</h2>
    <div class="border border-dark p-3">
        <h4>Livre / Article</h4>
        <div class="container">
            {% include 'reviewer/form/header.html' %}
            {{ form.title.label }}
            {{ form.title }}
            {{ form.description.label }}
            {{ form.description }}
            {{ form.image.label }}
            {{ form.image }}
        </div>
        <hr>
        <h4>Critique</h4>
        <div class="container">
            {{ form.rating.label }}
            {{ form.rating }}
            {{ form.headline.label }}
            {{ form.headline }}
            {{ form.body.label }}
            {{ form.body }}
           {% include 'reviewer/form/footer.html' %}
        </div>
    </div>
{% endblock content %}

reviewer/templates/reviewer/detail_review.html
{% load static %}

<div class="col text-end">
    <p>{{ review.time_created }}</p>
</div>
<p>{{ review.headline }} - 
    <img src="{% static 'reviewer/image/'|add:image %}" alt="LitReview" width="60" height="15">
</p>
{% if review.body %}
    <p>Commentaire : {{ review.body }}</p>
{% endif %}
<div class="col ticket_review border border-dark p-3 mx-3 mb-3">
    {% include 'reviewer/detail_ticket.html' with ticket=review.ticket %}
</div>

reviewer/templates/reviewer/detail_ticket.html
<p>Ticket - {{ ticket.user }}</p>
<p>Titre : {{ ticket.title }}</p>
{% if ticket.description %}
    <p>Description : {{ ticket.description }}</p>
{% endif %}
{% if ticket.image %}
    <div class="text-center">
        <img class="rounded mx-auto w-25" src="{{ ticket.image.url }}" alt="ticket_image"/>
    </div>
{% endif %}

reviewer/templates/reviewer/flux.html
{% extends 'reviewer/tickets_and_reviews.html' %}

{% block content_title %}
    Votre flux
{% endblock %}
{% block content_header %}
    <div class="row justify-content-center gap-3 my-3">
        <a class="btn btn-outline-success col-3" href="{% url 'reviewer:create_ticket' %}">Créer un ticket</a>
        <a class="btn btn-outline-success col-3" href="{% url 'reviewer:create_review_ticket' %}">Créer une critique</a>
    </div>
{% endblock %}
{% block review_button %}
    {% if rev.ticket.user.id != request.user.id and rev.user.id != request.user.id %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <a class="btn btn-outline-dark" href="{% url 'reviewer:create_review' rev.ticket_id %}">Créer une critique</a>
        </div>
    {% endif %}
{% endblock %}

{% block ticket_button %}
    {% if ticket.user.id != request.user.id %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <a class="btn btn-outline-dark" href="{% url 'reviewer:create_review' ticket.id %}">Créer une critique</a>
        </div>
    {% endif %}
{% endblock %}

reviewer/templates/reviewer/list_followed_user.html
{% extends 'squeleton.html' %}

{% block title %}
    <title>Abonnements</title>
{% endblock title %}

{% block content %}
    {% if error %}
        <div class="alert alert-danger">
           {{ error }}
        </div>
    {% endif %}
    <h4>Suivre d'autres utilisateurs</h4>
    <form class="row g-3 m-3" action="" method="GET">
        <div class="col">
            <input class="form-control border-dark" type="search" name="name" placeholder="Recherche d'utilisateur" required>
        </div>
        <div class="col-3">
            <input class="form-control btn btn-outline-success" type="submit" value="Envoyer">
        </div>
    </form>
    {% if searched_users %}
    <table class="table table-striped table-bordered border-dark">
        {% for user in searched_users %}
        <tr>
            <td class="align-middle">{{ user.username }}</td>
            <td class="col-md-2 text-center">
                <a class="btn btn-primary btn-sm" href="{% url 'reviewer:subscribe' %}?user_id={{ user.id }}">
                    S'abonner
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
    <hr>
    {% if followed_users %}
    <p>Abonnements</p>
    <table class="table table-striped table-bordered border-dark">
        <tbody>
        {% for followed_user in followed_users %}
            <tr>
                <td class="align-middle">{{ followed_user.followed_user }}</td>
                <td class="col-md-2 text-center">
                    <a class="btn btn-danger btn-sm" href="{% url 'reviewer:unsubscribe' %}?user_id={{ followed_user.id }}">
                        Se désabonner
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        <h4>Vous n'êtes pas abonné !</h4>
    {% endif %}
    <hr>
    <p>Abonnés</p>
    <table class="table table-striped table-bordered border-dark">
        <tbody>
        {% for following_user in following_users %}
            <tr>
                <td>{{ following_user.user }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

reviewer/templates/reviewer/list_ticket.html
{% extends 'squeleton.html' %}

{% block title %}
    <title>Liste de ticket</title>
{% endblock title %}

{% block content %}
    <p>Flux</p>
    {% for element in flux_elements %}
        {% comment %}
            element is either a review
        {% endcomment %}
        {% if element.review %}
            {% with rev=element.review %}
            <div class="review">
                {% if request.user == rev.user %}
                    <p>Vous avez publié une critique</p>
                {% else %}
                    <p>{{ rev.user }} a publié une critique</p>
                {% endif %}
                <p>{{ rev.time_created }}</p>
                <p>{{ rev.headline }} - {{ rev.rating }}</p>
                {% comment %}
                    containing a ticket
                {% endcomment %}
                <div class="ticket_review">
                    {% include 'reviewer/detail_ticket.html' with ticket=rev.ticket %}
                </div>
                {% if element.button == 'create' %}
                    <a href="{% url 'reviewer:create_review' rev.ticket_id %}">Créer une critique</a>
                {% elif element.button == 'modify' %}
                    <a href="{% url 'reviewer:update_review' rev.id %}">Modifier</a>
                {% endif %}
            </div>
            {% endwith %}

        {% comment %}
            or element is a ticket
        {% endcomment %}
        {% else %}
            {% with ticket=element.ticket%}
            <div class="ticket">
                {% if request.user == ticket.user %}
                    <p>Vous avez demandé une critique</p>
                {% else %}
                    <p>{{ ticket.user }} a demandé une critique</p>
                {% endif %}
                <p>{{ ticket.time_created }}</p>
                <p>{{ ticket.title }} - {{ ticket.rating }}</p>
                {% if element.button == 'create' %}
                    <a href="{% url 'reviewer:create_review' ticket.id %}">Modifier</a>
                {% elif element.button == 'modify' %}
                    <a href="{% url 'reviewer:update_ticket' ticket.id %}">Modifier</a>
                {% endif %}
            </div>
            {% endwith %}
        {% endif %}
    {% endfor %}
{% endblock content %}

reviewer/templates/reviewer/login.html
{% extends 'squeleton.html' %}

{% block title %}
    <title>Connexion</title>
{% endblock title %}

{% block content %}
    <div class="container-md text-center">
        <div class="row align-items-center">
            <div class="col">
                <h2 class="mb-3">Inscrivez-vous maintenant :</h2>
                <a class="btn btn-primary" role="button" href="{% url 'reviewer:register' %}">S'inscrire</a>
            </div>
            <div class="col">
                <h2 class="mb-3">Connectez-vous :</h2>
                {% include 'reviewer/form/full.html' %}
            </div>
        </div>
    </div>

{% endblock content %}

reviewer/templates/reviewer/my_posts.html
{% extends 'reviewer/tickets_and_reviews.html' %}

{% block content_title %}
    Vos posts
{% endblock %}
{% block review_button %}
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-outline-dark" href="{% url 'reviewer:update_review' rev.id %}">Modifier</a>
        <a class="btn btn-outline-danger" href="{% url 'reviewer:delete_review' rev.id %}">Supprimer</a>
    </div>
{% endblock %}

{% block ticket_button %}
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-outline-dark" href="{% url 'reviewer:update_ticket' ticket.id %}">Modifier</a>
        <a class="btn btn-outline-danger" href="{% url 'reviewer:delete_ticket' ticket.id %}">Supprimer</a>
    </div>
{% endblock %}

reviewer/templates/reviewer/register.html
{% extends 'squeleton.html' %}

{% block title %}
    <title>Inscription</title>
{% endblock title %}

{% block content %}
    
    <div class="container text-center col-sm-10 col-md-3">
        <h2>Inscrivez-vous</h2>
        {% include 'reviewer/form/full.html' %}
        <a href="{% url 'reviewer:login' %}">Déjà inscrit ? Se connecter</a>
    </div>
    
{% endblock content %}

reviewer/templates/reviewer/tickets_and_reviews.html
{% extends 'squeleton.html' %}
{% load static %}

{% block title %}
    <title>Liste de ticket</title>
{% endblock title %}

{% block content %}
    <h2>
        {% block content_title %}
        {% endblock %}
    </h2>
    {% block content_header %}
    {% endblock %}
    {% for element in flux_elements %}
        {% comment %}
            element is either a review containing a ticket
        {% endcomment %}
        {% if element.review %}
            {% with rev=element.review %}
            <div class="review border border-dark p-3">
                <div class="row">
                    <div class="col">
                        {% if request.user == rev.user %}
                            <p>Vous avez publié une critique</p>
                        {% else %}
                            <p>{{ rev.user }} a publié une critique</p>
                        {% endif %}
                    </div>
                    {% include 'reviewer/detail_review.html' with review=rev image=element.rating %}
                </div>
                {% block review_button %}
                {% endblock %}
            </div>
            {% endwith %}

        {% comment %}
            or element is a ticket
        {% endcomment %}
        {% else %}
            {% with ticket=element.ticket%}
            <div class="ticket border border-dark p-3">
                <div class="row">
                    <div class="col">
                        {% if request.user == ticket.user %}
                            <p>Vous avez demandé une critique</p>
                        {% else %}
                            <p>{{ ticket.user }} a demandé une critique</p>
                        {% endif %}
                    </div>
                    <div class="col text-end">
                        <p>{{ ticket.time_created }}</p>
                    </div>
                </div>
                {% include 'reviewer/detail_ticket.html' with ticket=ticket %}
                {% block ticket_button %}
                {% endblock %}
            </div>
            {% endwith %}
        {% endif %}
        <br>
        
    {% endfor %}
{% endblock content %}

reviewer/templates/reviewer/update_review.html
{% extends 'squeleton.html' %}

{% block title %}
    <title>Mise à jour de review</title>
{% endblock title %}

{% block content %}
    {% include 'reviewer/form/full.html' %}
    
{% endblock content %}

reviewer/templates/reviewer/update_ticket.html
{% extends 'squeleton.html' %}

{% block title %}
    <title>Mise à jour de ticket</title>
{% endblock title %}

{% block content %}
    {% include 'reviewer/form/full.html' %}
    
{% endblock content %}